# 作業 

### 1. 請比較對一個 100x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。




In [1]:
#引進套件
import numpy as np

In [2]:
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)
Z

array([[[9, 1, 3, ..., 4, 5, 9],
        [2, 6, 7, ..., 2, 5, 6],
        [4, 0, 6, ..., 7, 9, 0],
        ...,
        [2, 1, 4, ..., 9, 0, 8],
        [5, 1, 9, ..., 9, 7, 9],
        [1, 8, 3, ..., 9, 8, 3]],

       [[7, 0, 4, ..., 6, 3, 1],
        [1, 8, 3, ..., 8, 1, 2],
        [4, 1, 0, ..., 5, 0, 3],
        ...,
        [7, 2, 0, ..., 6, 0, 7],
        [3, 0, 1, ..., 8, 9, 0],
        [8, 2, 3, ..., 0, 3, 8]],

       [[7, 3, 5, ..., 8, 2, 3],
        [3, 6, 4, ..., 2, 4, 2],
        [1, 6, 8, ..., 1, 3, 6],
        ...,
        [9, 0, 0, ..., 1, 4, 5],
        [7, 6, 2, ..., 9, 7, 4],
        [0, 2, 7, ..., 4, 5, 9]],

       ...,

       [[1, 4, 6, ..., 0, 4, 4],
        [5, 5, 8, ..., 3, 5, 2],
        [0, 1, 4, ..., 3, 7, 5],
        ...,
        [8, 2, 5, ..., 2, 6, 2],
        [3, 4, 8, ..., 5, 4, 0],
        [4, 0, 0, ..., 1, 4, 3]],

       [[8, 2, 5, ..., 7, 7, 1],
        [8, 0, 2, ..., 3, 1, 6],
        [4, 5, 5, ..., 7, 4, 3],
        ...,
        [8, 1, 3, ..., 

timeit是python內建的模組; 主要用來測量幾行簡短程式碼或一個函式的執行時間

In [3]:
%%timeit #%%timeit [-n<N> -r<R> [-t|-c] -q -p<P> -o] setup_code code code…
for i in Z.flat: #將陣列攤平後進行迴圈運算 
    i+=1 #每一個元素+1的時間比較

240 ms ± 34.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### 2. 如何從一個陣列中，找出出現頻率最高的數值與位置？


In [4]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.sort(Z)) #將array排序好以便查看

[6 3 6 8 5 8 8 0 1 4 3 6 3 3 6 3 2 7 3 6 8 7 3 0 9 2 6 4 3 6 1 3 7 3 4 5 3
 5 6 0 4 7 3 3 9 7 5 9 9 0]
[0 0 0 0 1 1 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 4 4 4 4 5 5 5 5 6 6 6 6 6 6 6 6
 7 7 7 7 7 8 8 8 8 9 9 9 9]


可以使用np.bincount()方法找出numpy的眾數，範例如下:<br>
#x = np.array([0,1,1,3,2,1,7]) <br>
可以看到x中最大的數為7，因此bin的數量為8，那麼它的索引值為0->7<br>
#np.bincount(x) <br>
輸出結果為：array([1,3,1,1,0,0,0,1]) <br>
表示索引0出現了1次，索引1出現了3次......索引5出現了0次......<br>

In [5]:
np.bincount(Z) #可以看到1的出現次數最多

array([ 4,  2,  2, 13,  4,  4,  8,  5,  4,  4], dtype=int64)

In [6]:
mode=np.bincount(Z).argmax() #可以看到1出現的次數是最多的
print(mode)

3


In [7]:
np.where(Z==mode) #找出所有眾數的位置

(array([ 1, 10, 12, 13, 15, 18, 22, 28, 31, 33, 36, 42, 43], dtype=int64),)

### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


list() 只會把第一層的元素轉換成 List，多層的話只有第一層會轉；<br>
tolist() 才能達成多層的型態轉換。

In [8]:
a = np.random.randint(10, size=6) 
print(a)
print(a.tolist())
print(list(a))
#一維陣列的結果會一樣

[5 4 9 2 7 3]
[5, 4, 9, 2, 7, 3]
[5, 4, 9, 2, 7, 3]


In [9]:
b = np.random.randint(10, size=(3,4)) 
print(b)
print(b.tolist())

print(list(b)) #二維陣列就只會有第一層轉而已

list_b=[] #用來儲存轉換b的空陣列
for row in b:
    transfer=list(row)
    list_b.append(transfer)
print(list_b) #達成tolist()效果

[[1 8 1 3]
 [4 8 2 5]
 [0 5 3 1]]
[[1, 8, 1, 3], [4, 8, 2, 5], [0, 5, 3, 1]]
[array([1, 8, 1, 3]), array([4, 8, 2, 5]), array([0, 5, 3, 1])]
[[1, 8, 1, 3], [4, 8, 2, 5], [0, 5, 3, 1]]


In [10]:
c = np.random.randint(10, size=(2,3,2)) 
print(c)
print(c.tolist())
print(list(c)) #三維陣列就只有第一層會轉而已

list_c=[] #用來儲存轉換c的空陣列
for i in c:
    for j in i:
        transfer=list(j)
        list_c.append(transfer)
print(list_c) #達成tolist()效果但會少一層qq

[[[5 7]
  [1 6]
  [4 8]]

 [[0 7]
  [8 4]
  [2 1]]]
[[[5, 7], [1, 6], [4, 8]], [[0, 7], [8, 4], [2, 1]]]
[array([[5, 7],
       [1, 6],
       [4, 8]]), array([[0, 7],
       [8, 4],
       [2, 1]])]
[[5, 7], [1, 6], [4, 8], [0, 7], [8, 4], [2, 1]]
