# [作業目標]

1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```

2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？

3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？

# 作業 

### 1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```
ANS:<br>
(a + a)=[40,60,80,100]<br>
(a + b)=[21,32,43,54]<br>
(a + c)=[21,31,41,51]<br>
(a + d)=[21,31,41,51]<br>
(a + e)不符合廣播原則，故無法計算


In [1]:
import numpy as np
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
print(a + a)
print(a + b)
print(a + c)
print(a + d)
#print(a + e)會顯示錯誤

[ 40  60  80 100]
[21 32 43 54]
[21 31 41 51]
[21 31 41 51]


### 2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？


In [2]:
# 記得先 Import 正確的套件
import numpy as np

In [3]:
A = np.ones(3)*1
B = np.ones(3)*2
print(A)
print(B)

#不使用迴圈
print((A+B)*(-A/2))

#使用迴圈
C=[]
i=0
while i<=2:
    C.append((A[i]+B[i])*(-A[i]/2))
    i+=1
print(C)

[1. 1. 1.]
[2. 2. 2.]
[-1.5 -1.5 -1.5]
[-1.5, -1.5, -1.5]


### 3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？


In [4]:
A = np.ones((1,6))
B = np.ones((6,1))
print(A)
print(B)
print('內積:\n',np.dot(A,B))
print('外積:\n',np.outer(A,B))

[[1. 1. 1. 1. 1. 1.]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
內積:
 [[6.]]
外積:
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
