# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [1]:
import numpy as np

In [2]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
print(np.empty((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


zeros函式為依照傳入的形狀引數，建立元素全是0的陣列。<br>
empty函式則是不需要給定起始值，但依照傳入的形狀引數建立元素值隨機指定的陣列；empty的資料並未指定，故元素值為0或1只是剛好。<br>
會設計兩種方法是因為zeros是要在固定形狀的陣列下指定元素為0、empty則是在固定形狀的陣列產生隨機元素所用。

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [4]:
# 先Import套件
from numpy.random import default_rng
rng=default_rng()

In [5]:
#產生一組2x3的隨機亂數
a= rng.random((2, 3))
a*=100 #*100讓他變有整數
print(a)

[[45.22501577 23.86246042 96.56661233]
 [74.92538329 23.74711438 28.32106416]]


In [6]:
for i in range(2):
    for j in range(3):
        a[i,j]=int(a[i,j])
print(a)

[[45. 23. 96.]
 [74. 23. 28.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [7]:
m = 20
n = 40
a=rng.random((2,3))*(n-m) 
b=a+m
print(b)

[[33.13268003 33.42951787 33.30223176]
 [37.09630085 31.73225815 37.9866221 ]]
