# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```
ANS:三種方法出來的結果都相同。



In [1]:
import numpy as np
a=np.arange(1,10,2)
print(a)
print(a.sum())
print(np.sum(a))
print(sum(a))

[1 3 5 7 9]
25
25
25


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [2]:
#最小最大值正規化：將資料等比例縮放到 [0, 1] 區間中，可利用下列公式進行轉換：
#Xnom=(X-Xmin)/(Xmax-Xmin)

In [3]:
A = np.random.random((5, 5))
A

array([[8.33082276e-01, 1.86328333e-01, 3.65718658e-01, 8.96776159e-01,
        1.16632899e-01],
       [4.33203697e-01, 4.75844232e-01, 4.04505169e-04, 3.30903463e-01,
        4.71505081e-01],
       [6.44338733e-01, 4.64132692e-01, 1.14671211e-01, 4.39835462e-01,
        5.71798720e-01],
       [9.11277196e-01, 8.75581761e-01, 5.03403260e-01, 8.02279118e-01,
        4.92883458e-01],
       [9.53549982e-01, 8.43204058e-01, 7.64418520e-02, 9.00142005e-01,
        1.55061306e-01]])

In [4]:
A_nom=((A-np.nanmin(A))/(np.nanmax(A)-np.nanmin(A)))
A_nom

array([[0.87361037, 0.19506343, 0.38327219, 0.9404353 , 0.12194193],
       [0.45407464, 0.49881129, 0.        , 0.34674556, 0.49425884],
       [0.67558861, 0.48652404, 0.1198838 , 0.46103241, 0.59948269],
       [0.95564918, 0.91819903, 0.52772506, 0.841293  , 0.51668813],
       [1.        , 0.88422971, 0.07977517, 0.9439666 , 0.16225939]])

### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [5]:
#引進新版套件
from numpy.random import default_rng
rng=default_rng()
B=rng.integers(0,100,size=10) #建立長度為10的0~100正整數向量
print(B)
index_max=np.argmax(B) #np.argmax()可找出array最大值的索引
B[index_max]=-1 #將該索引的值改成=-1
print(B)


[ 2 64 98 90 57 68 47 63  7 47]
[ 2 64 -1 90 57 68 47 63  7 47]
