# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [1]:
import numpy as np

In [2]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
print(np.empty((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


zeros函式為依照傳入的形狀引數，建立元素全是0的陣列。<br>
empty函式則是不需要給定起始值，但依照傳入的形狀引數建立元素值隨機指定的陣列；empty的資料並未指定，故元素值為0或1只是剛好。<br>
會設計兩種方法是因為zeros是要在固定形狀的陣列下指定元素為0、empty則是在固定形狀的陣列產生隨機元素所用。

###參考解答###<br>
np.zeros((2, 3)) 會產生真正的 0<br>
np.empty((2, 3)) 會產生一個近似於 0 的陣列<br>
np.empty 可以用於只是想要初始化，但之後就會數值覆寫過的形況。

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [4]:
# 先Import套件
from numpy.random import default_rng
rng=default_rng()

In [5]:
#產生一組2x3的隨機亂數
a= rng.random((2, 3))
a*=100 #*100讓他變有整數
print(a)

[[85.34500358 18.4427652  13.46397773]
 [21.96693752 77.29077737 77.77681364]]


In [6]:
for i in range(2):
    for j in range(3):
        a[i,j]=int(a[i,j])
print(a)

[[85. 18. 13.]
 [21. 77. 77.]]


###參考解答###<br>
使用'round()'-使數值五捨六入變整數<br>
print(a.round(())<br>
print(np.round(a))

In [7]:
print(a.round())
print(np.round(a))

[[85. 18. 13.]
 [21. 77. 77.]]
[[85. 18. 13.]
 [21. 77. 77.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [8]:
m = 20
n = 40
a=rng.random((2,3))*(n-m) 
a+=m
b=a.round()
print(b)

[[24. 22. 22.]
 [38. 33. 31.]]


###參考解答###<br>
原本的 random 會產一個介於 0 - 1 數字組成的 2x3 矩陣<br>
題目要求希望把 0 - 1 的數字轉換到 20 - 40 的範圍。<br>
這邊的做法是先把範圍放大到 m - n 之間，再平移 +m

In [9]:
m = 20
n = 40
a = np.random.rand(2, 3) * (n - m)
b = a
print((a - b % 1) + m)

[[30. 21. 37.]
 [36. 31. 33.]]
