In [1]:
import numpy as np

In [2]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
Array=np.arange(0,21,1)
print(Array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [3]:
#2.呈上題，將以上數列取出偶數。
Even=Array[0::2]
print(Even)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [4]:
#3.呈1題，將數列取出3的倍數。
mul_3=Array[3::3]
print(mul_3)

[ 3  6  9 12 15 18]


[簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？<br>
Ans:<br>
list()是將元組(Tuple)轉換為列表(List)，
因元組的元素值不能修改，只能將數據中的最外層進行list操作。<br>
tolist()是數組或矩陣轉為List形式，
因此能將輸入進去的數據全部list化。



In [9]:
#5.請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）
print('陣列Array的維度數目為:',Array.ndim)
print('陣列Array的元素數目為:',Array.size)
print('陣列Array每個元素的記憶體使用量為:',Array.itemsize)

陣列Array的維度數目為: 1
陣列Array的元素數目為: 21
陣列Array每個元素的記憶體使用量為: 4


In [26]:
#6.如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。
a=Array.reshape((3,7))
print(a)
#
new_a0=[]
for i in range(7):
    new_a0.append(a[0,i])
new_a1=[]
for j in range(7):
    new_a1.append(a[1,j])
new_a2=[]
for k in range(7):
    new_a2.append(a[2,k])
new_a_list=[new_a0,new_a1,new_a2]
print(new_a_list)
print(a.tolist())

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]


[[0, 1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12, 13], [14, 15, 16, 17, 18, 19, 20]]
[[0, 1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12, 13], [14, 15, 16, 17, 18, 19, 20]]
